// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmgymlbyebdqfwkovwvd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtZ3ltbGJ5ZWJkcWZ3a292d3ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ1NDUwOTksImV4cCI6MjA1MDEyMTA5OX0.s4-gUjINoe_VRE4nK-weSEidm5JjEJThJFDKzQgtmfk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);